# valhalla - primary configuration
# check documentation for how to use these options
# https://github.com/mmeyer2k/valhalla/blob/master/docs/configuration.md

#ip4: 10.1.10.64
#ip6: 2603:300c:1c00:9600:a00:27ff:fe45:9c70
#socks5: socks5://127.0.0.1:9050
memory: 512
cpus: 2
cpuexecutioncap: 90
mode: tight